global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'apigateway'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['apigateway:4000']
    
  - job_name: 'smartmeter'
    metrics_path: '/metrics'  # Assuming simulator exposes this
    static_configs:
      - targets: ['smartmeter:8080']
